version: "2"

run:
  timeout: 5m

linters:
  enable:
    - exhaustive
    - errorlint
    - forcetypeassert
    - predeclared
    - nilerr
    - nilnesserr
    - modernize
    - intrange
    - exptostd
    - copyloopvar
    - unconvert
    - misspell

linters-settings:
  exhaustive:
    default-signifies-exhaustive: false

formatters:
  enable:
    - gofmt
    - goimports
