// Package main provides the imgo CLI tool for transpiling ImGo source files into immutable Go.
package main

import (
	"errors"
	"fmt"
	"go/parser"
	"go/printer"
	"go/token"
	"os"
	"path/filepath"
	"strings"

	"github.com/rg/imgo/pkg/transpiler"
)

func main() {
	if err := run(os.Args); err != nil {
		fmt.Fprintf(os.Stderr, "Error: %v\n", err)
		os.Exit(1)
	}
}

func run(args []string) error {
	if len(args) < 2 {
		return errors.New("usage: imgo <path>")
	}

	targetPath := args[1]
	fset := token.NewFileSet()

	var files []string
	err := filepath.Walk(targetPath, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}
		if info.IsDir() || !strings.HasSuffix(info.Name(), ".im") {
			return nil
		}
		files = append(files, path)
		return nil
	})

	if err != nil {
		return err
	}

	if len(files) == 0 {
		return fmt.Errorf("no .im files found in %s", targetPath)
	}

	for _, path := range files {
		f, err := parser.ParseFile(fset, path, nil, parser.ParseComments)
		if err != nil {
			return fmt.Errorf("error parsing %s: %w", path, err)
		}

		// Run the full transpilation pipeline (Validate -> Rewrite)
		f, err = transpiler.Transpile(fset, f)
		if err != nil {
			return fmt.Errorf("transpilation error in %s:\n%w", path, err)
		}

		// Create new Go file name
		newPath := strings.TrimSuffix(path, ".im") + "_imgo_gen.go"

		newFile, err := os.Create(newPath)
		if err != nil {
			return fmt.Errorf("error creating file %s: %w", newPath, err)
		}
		defer func() { _ = newFile.Close() }()

		_, _ = fmt.Fprintf(newFile, "// Code generated by imgo. DO NOT EDIT.\n")
		_ = printer.Fprint(newFile, fset, f)
		fmt.Printf("Generated: %s\n", newPath)
	}
	return nil
}
