// Package main provides the imgo CLI tool for transpiling ImGo source files into immutable Go.
package main

import (
	"errors"
	"fmt"
	"go/parser"
	"go/printer"
	"go/token"
	"log"
	"os"
	"path/filepath"
	"runtime"
	"strings"
	"sync"

	"github.com/rg/imgo/pkg/transpiler"
)

const minArgs = 2

var (
	errUsage     = errors.New("usage: imgo <path>")
	errNoImFiles = errors.New("no .im files found")
)

func main() {
	err := run(os.Args)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error: %v\n", err)
		os.Exit(1)
	}
}

func run(args []string) error {
	if len(args) < minArgs {
		return errUsage
	}

	targetPath := args[1]
	fset := token.NewFileSet()

	files, err := collectFiles(targetPath)
	if err != nil {
		return err
	}
	if len(files) == 0 {
		return fmt.Errorf("%w in %s", errNoImFiles, targetPath)
	}

	return runParallel(fset, files)
}

func collectFiles(targetPath string) ([]string, error) {
	var files []string
	err := filepath.Walk(targetPath, func(path string, info os.FileInfo, err error) error { //nolint:gosec
		if err != nil {
			return err
		}
		if info.IsDir() || !strings.HasSuffix(info.Name(), ".im") {
			return nil
		}
		files = append(files, path)

		return nil
	})

	return files, err
}

func runParallel(fset *token.FileSet, files []string) error {
	filesCh := make(chan string, len(files))
	for _, path := range files {
		filesCh <- path
	}
	close(filesCh)

	var wg sync.WaitGroup
	errCh := make(chan error, len(files))
	numWorkers := runtime.NumCPU()

	for range numWorkers {
		wg.Go(func() {
			for path := range filesCh {
				err := processFile(fset, path)
				if err != nil {
					errCh <- err
				}
			}
		})
	}

	wg.Wait()
	close(errCh)

	return <-errCh
}

func processFile(fset *token.FileSet, path string) error {
	f, err := parser.ParseFile(fset, path, nil, parser.ParseComments)
	if err != nil {
		return fmt.Errorf("error parsing %s: %w", path, err)
	}

	// Run the full transpilation pipeline (Validate -> Rewrite)
	f, err = transpiler.Transpile(fset, f)
	if err != nil {
		return fmt.Errorf("transpilation error in %s:\n%w", path, err)
	}

	// Create new Go file name
	newPath := strings.TrimSuffix(path, ".im") + "_imgo_gen.go"

	newFile, err := os.Create(newPath) //nolint:gosec
	if err != nil {
		return fmt.Errorf("error creating file %s: %w", newPath, err)
	}

	defer func() {
		err := newFile.Close()
		if err != nil {
			log.Printf("error closing file %s: %v", newPath, err)
		}
	}()

	_, err = fmt.Fprintf(newFile, "// Code generated by imgo. DO NOT EDIT.\n")
	if err != nil {
		return fmt.Errorf("error writing header to %s: %w", newPath, err)
	}
	err = printer.Fprint(newFile, fset, f)
	if err != nil {
		return fmt.Errorf("error writing transpiled code to %s: %w", newPath, err)
	}

	log.Printf("Generated: %s", newPath)

	return nil
}
