// Package main provides the imgo CLI tool for transpiling ImGo source files into immutable Go.
package main

import (
	"errors"
	"fmt"
	"go/parser"
	"go/printer"
	"go/token"
	"log"
	"os"
	"path/filepath"
	"runtime"
	"strings"
	"sync"

	"github.com/rg/imgo/pkg/transpiler"
)

func main() {
	if err := run(os.Args); err != nil {
		fmt.Fprintf(os.Stderr, "Error: %v\n", err)
		os.Exit(1)
	}
}

func run(args []string) error {
	if len(args) < 2 {
		return errors.New("usage: imgo <path>")
	}

	targetPath := args[1]
	fset := token.NewFileSet()

	var files []string
	err := filepath.Walk(targetPath, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}
		if info.IsDir() || !strings.HasSuffix(info.Name(), ".im") {
			return nil
		}
		files = append(files, path)
		return nil
	})

	if err != nil {
		return err
	}

	if len(files) == 0 {
		return fmt.Errorf("no .im files found in %s", targetPath)
	}

	filesCh := make(chan string, len(files))
	for _, path := range files {
		filesCh <- path
	}
	close(filesCh)

	var wg sync.WaitGroup
	errCh := make(chan error, len(files))
	numWorkers := runtime.NumCPU()

	for range numWorkers {
		wg.Go(func() {
			for path := range filesCh {
				if err := processFile(fset, path); err != nil {
					errCh <- err
				}
			}
		})
	}

	wg.Wait()
	close(errCh)

	if err := <-errCh; err != nil {
		return err
	}

	return nil
}

func processFile(fset *token.FileSet, path string) error {
	f, err := parser.ParseFile(fset, path, nil, parser.ParseComments)
	if err != nil {
		return fmt.Errorf("error parsing %s: %w", path, err)
	}

	// Run the full transpilation pipeline (Validate -> Rewrite)
	f, err = transpiler.Transpile(fset, f)
	if err != nil {
		return fmt.Errorf("transpilation error in %s:\n%w", path, err)
	}

	// Create new Go file name
	newPath := strings.TrimSuffix(path, ".im") + "_imgo_gen.go"

	newFile, err := os.Create(newPath)
	if err != nil {
		return fmt.Errorf("error creating file %s: %w", newPath, err)
	}

	defer func() {
		err := newFile.Close()
		if err != nil {
			log.Printf("error closing file %s: %v", newPath, err)
		}
	}()

	if _, err := fmt.Fprintf(newFile, "// Code generated by imgo. DO NOT EDIT.\n"); err != nil {
		return fmt.Errorf("error writing header to %s: %w", newPath, err)
	}
	if err := printer.Fprint(newFile, fset, f); err != nil {
		return fmt.Errorf("error writing transpiled code to %s: %w", newPath, err)
	}

	fmt.Printf("Generated: %s\n", newPath)
	return nil
}
